# Import NumPy
import numpy as np
# a) 1d
array1 = np.array([10, 20, 30, 40, 50])
# b) 2d
array2 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Display 1D array
print("1D Array:")
print(array1)
print("Shape:", array1.shape)
print("Data Type:", array1.dtype)
# Display 2D array
print("\n2D Array:")
print(array2)
print("Shape:", array2.shape)
print("Data Type:", array2.dtype)